# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2017'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- script: pwd
  displayName: Pwd
 
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    packagesDirectory: '../packages'

- script: tree
  displayName: Show Directory

- script: tree ../packages
  displayName: Show Packages

- script: .\packages\Wyam.1.5.1\tools\net462\wyam.exe build
  displayName: Wyam Build
