# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2017'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- script: git checkout master
  displayName: Git checkout
  
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install Blog\packages.config -Verbosity Detailed -NonInteractive -OutputDirectory packages'

- script: .\packages\Wyam.1.5.1\tools\net462\wyam.exe build --packages-path packages --use-local-packages
  displayName: Wyam Build
  
- script: tree
  displayName: Show Directory  
  
- script: git config --global user.email "azure-pipelines[bot]@users.noreply.github.com"
  displayName: Git set email
  
- script: git config --global user.name "azure-pipelines[bot]"
  displayName: Git set name
  
- script: git add .
  displayName: Git add track
  
- script: git status
  displayName: Git diff
  
- script: git commit -m "Update Docs"
  displayName: Git commit
  
- script: git push origin master -c http.extraheader="AUTHORIZATION: basic $Env:SYSTEM_ACCESSTOKEN"
  displayName: Git push
